--- #YAML:1.0
name: Scriptalicious
version: 1.04_01
author:
  - Sam Vilain, samv@cpan.org
abstract: Delicious scripting goodies
license: perl
recommends:
  Term::ReadKey: 0
  Text::Wrap: 0
  Time::HiRes: 0
  YAML: 0
build_requires:
  Test::More: 0
provides:
  Scriptalicious:
    file: lib/Scriptalicious.pm
    version: 1.04_01
generated_by: Module::Build version 0.25
